- name: リポジトリをインストール
  command: rpm -ih http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm creates=/etc/yum.repos.d/mysql-community.repo

- name: MySQLのパッケージをインストール
  yum: name={{ item }} state=present enablerepo="mysql57-community" state=installed
  with_items:
    - mysql-community-client
    - mysql-community-common
    - mysql-community-devel
    - mysql-community-libs
    - mysql-community-libs-compat
    - mysql-community-server

- name: MySQL-pythonをインストール
  yum: name={{ item }} state=present enablerepo="epel" state=installed
  with_items:
    - MySQL-python
    - libselinux-python
    - libsemanage-python
  tags: mysql

- name: MySQL 起動設定
  service: name=mysqld state=started enabled=yes

- name: 初期パスワードを取得
  shell: |
    grep 'password is generated' /var/log/mysqld.log | awk -F'root@localhost: ' '{print $2}'
  register: init_pwd

- name: 一時設定ファイルを設置
  template: src=.tmp.my.cnf dest=/root/.tmp.my.cnf owner=root mode=0600
  register: is_exists

- name: パスワードポリシーの変更
  shell: |
    mysql -u root -p{{ init_pwd.stdout }} --connect-expired-password -e "SET GLOBAL validate_password_policy=LOW; SET GLOBAL validate_password_length = 4"
  failed_when: is_exists.stat.md5 is defined

- name: rootユーザーのパスワードを変更
  shell: |
    mysql --defaults-file=/root/.tmp.my.cnf -e "ALTER USER 'root'@'localhost' IDENTIFIED BY  '{{ mysql["root_password"] }}' "
  failed_when: is_exists.stat.md5 is defined

- name: rootユーザーのmy.cnfを作成
  template: src=.my.cnf dest=/root/.my.cnf owner=root mode=0600
  failed_when: is_exists.stat.md5 is defined

- name: ユーザーを追加
  mysql_user:
    name: "{{ user['name'] }}"
    password: "{{ user['password'] }}"
    host: "{{ item }}"
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - "localhost"
    - "127.0.0.1"
    - "::1"
    - "%"
  ignore_errors: true
  tags: [mysql]

- name: DBを作成
  shell: |
    mysql -u {{ user['name'] }} -p{{ user['password'] }} -e "CREATE DATABASE IF NOT EXISTS {{ mysql['dbname'] }};"
  tags: mysql