---
user:
  name: vagrant
  group: vagrant
  password: vagrant

project: handson
hostname: handson.local
project_root: "/home/{{ user['name'] }}"
document_root: "{{ project_root }}/www/html"
log_root: /var/log
charset: utf8