---
user:
  name: vagrant
  group: vagrant
  password: vagrant

project: handson
hostname: handson.local
project_root: "/home/{{ user.name }}"
document_root: "{{ project_root }}/www/html"
log_root: /var/log
charset: utf8

static:
  hostname: coding.handson.local
  document_root: "{{ project_root }}/dist/www/html/cording"

nginx:
  server_name: 192.168.33.50
  vhost_path: /etc/nginx/conf.d
  vhost_file: default.conf
  template: default.conf.j2

#httpd:
#  error_log: "{{ log_root }}/httpd/error_log"
#  access_log: "{{ log_root }}/httpd/access_log combined"

#wp:
#  sitename: handson
#  admin: dev
#  password: ^lS$9z)Y!uM&j0^Fa1qOl8iT
#  email: 'example@cinra.net'
#  theme: bootstrap
#  table_prefix: wp