---
- name: Handson環境をインストール
  # - include: webservers.yml
  hosts: localhost
  remote_user: vagrant
  become: yes
  vars_files:
    - ../host_vars/development.yml
  roles:
    #- ../roles/nginx
    #- ../roles/php
    - ../roles/db
    - ../roles/wp