---
- name: Handson環境をインストール
  # - include: webservers.yml
  hosts: localhost
  remote_user: vagrant
  become: yes
  vars_files:
    - ../host_vars/development.yml
  roles:
    #- ../roles/common
    - ../roles/nginx
    - ../roles/php
    # - ../roles/httpd

    # - ../roles/mysql