---
# file: provisioning/roles/nginx/tasks/main.yml
- name: Install nginx
  yum: name=nginx state=latest

- name: set auto start nginx
  #command: chkconfig nginx on
  command: systemctl enable nginx

- name: restart nginx
  #command: service nginx restart
  command: systemctl restart nginx

- name: Set default nginx site
  template: src={{ nginx.template }} dest={{ nginx.vhost_path }}/{{ nginx.vhost_file }}

#- name: Set nginx.conf
#  template: src={{ nginx['template'] }} dest=/etc/nginx/nginx.conf

#- name: Set virtual.conf
#  template: src={{ nginx['template'] }} dest={{ nginx['vhost_path'] }}/{{ nginx['vhost_file'] }}