---
# file: provisioning/roles/nginx/tasks/main.yml
- name: nginx - インストール
  yum: name=nginx state=latest

- name: nginx - 自動起動設定
  #command: chkconfig nginx on
  command: systemctl enable nginx

- name: nginx - 環境設定（vhost）
  template: src={{ nginx['template_default'] }} dest={{ nginx['vhost_path'] }}/{{ nginx['default_file'] }}

- name: nginx - 環境設定（PHP-FPM 連携用vhost）
  template: src={{ nginx['template_vhost'] }} dest={{ nginx['vhost_path'] }}/{{ nginx['vhost_file'] }}

- name: nginx - 設定をリロード
  #command: service nginx restart
  command: systemctl restart nginx
  #command: systemctl reload nginx


#- name: Set nginx.conf
#  template: src={{ nginx['template'] }} dest=/etc/nginx/nginx.conf

#- name: Set virtual.conf
#  template: src={{ nginx['template'] }} dest={{ nginx['vhost_path'] }}/{{ nginx['vhost_file'] }}

- name: Firewallにルールを追加
  command: firewall-cmd --add-service=http --permanent

- name: Firewallを再起動
  command: firewall-cmd --reload